<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="login"
    errors="1" failures="0" hostname="" id="" package="login" skipped="0"
    tests="1" time="0.06600" timestamp="Sat, 17 Jun 2017 05:49:57 GMT">
  
    <testcase name="Log in" classname="login" time="0.06600" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Login / Log in]:

  ReferenceError: user is not defined
    at Object.Log in (/home/ttt/Projects/nightwatch_17_06/tests/login.js:11:5)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
